version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-morph
    versions:
    - 10.0.0
    - 10.0.1
    - 9.1.0
